version: '3.8'

services:
  couchdb:
    image: couchdb:latest
    container_name: obsidian-livesync
    user: 0:0
    environment:
      - COUCHDB_USER=user
      - COUCHDB_PASSWORD=testitest
    volumes:
      - couchdb_data:/opt/couchdb/data
      - ../files/volumes/config/local.ini:/opt/couchdb/etc/local.ini

volumes:
  couchdb_data: