[variables]
main_domain = "${domain}"
username = "${username}"
password = "${password}"

[config]
env = [
"COUCHDB_USER=${username}",
"COUCHDB_PASSWORD=${password}"
]

[[config.mounts]]
filePath = "/volumes/config/local.ini"
content = """

"""


[[config.domains]]
serviceName = "couchdb"
port = 5984
host = "${main_domain}"
